# Generated by Django 5.0.2 on 2024-03-08 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0002_rename_employee_employee_employee_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='employee_Id',
            new_name='employee_id',
        ),
    ]
